"""Phase 8 section 6: the per-element transition table of the frozen Phase 7 Q-V scores (scaled input -> VAE round
trip), derived mechanically from research/qwen/qv/review/SCORES-FROZEN.csv and key-unblinded.json. Reads only; the
frozen files are not modified. Writes research/qwen/qv-reference/phase7-transitions.{json,md}.

Run: mflux/.venv/bin/python3.12 research/qwen/qv-reference/phase7_transitions.py"""
import csv
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
QV = ROOT / "research/qwen/qv/review"
OUT = ROOT / "research/qwen/qv-reference"
sys.path.insert(0, str(ROOT / "research/qwen/qq"))
from qq_blind import ELEMENTS  # noqa: E402

LEGIBLE = {"PRESERVED", "DEGRADED"}
ABBR = {"PRESERVED": "P", "DEGRADED": "D", "GARBLED": "G", "REMOVED": "R", "NA": "NA"}


def transition(i: str, r: str) -> str:
    li, lr = i in LEGIBLE, r in LEGIBLE
    if i == "NA" or r == "NA":
        return "NA"
    if not li and not lr:
        return "illegible -> illegible (scaling loss; stays lost)"
    if li and not lr:
        return "legible -> illegible (VAE loss, L)"
    if not li and lr:
        return "illegible -> legible (REVERSAL: the round trip reads where the scaled input did not)"
    if i == "PRESERVED" and r == "DEGRADED":
        return "legible -> legible (softened P -> D)"
    return "legible -> legible"


def main() -> None:
    frozen = QV / "SCORES-FROZEN.csv"
    key = json.loads((QV / "key-unblinded.json").read_text())
    rows = {r["id"]: r for r in csv.DictReader(frozen.open())}
    table = []
    for sheet, k in sorted(key.items(), key=lambda kv: (kv[1]["budget"], kv[1]["task"])):
        role = {k["A"]: rows[f"{sheet}-A"], k["B"]: rows[f"{sheet}-B"]}
        for n, element in enumerate(ELEMENTS[k["task"]], start=1):
            i, r = role["input"][f"t{n}"], role["roundtrip"][f"t{n}"]
            table.append({"budget": k["budget"], "task": k["task"], "element": f"t{n}", "sheet": sheet,
                          "description": element, "after_resize": i, "after_vae": r, "transition": transition(i, r)})
    summary = {}
    for b in (512, 1024):
        t = [x for x in table if x["budget"] == b]
        k_ = [x for x in t if x["after_resize"] in LEGIBLE]
        summary[b] = {
            "units": len(t),
            "legible_after_resize_K": len(k_),
            "lost_by_vae_L": sum(x["after_vae"] not in LEGIBLE for x in k_),
            "kept_from_K": sum(x["after_vae"] in LEGIBLE for x in k_),
            "reversals_illegible_to_legible": sum(x["after_resize"] not in LEGIBLE and x["after_vae"] in LEGIBLE for x in t),
            "legible_after_vae": sum(x["after_vae"] in LEGIBLE for x in t),
        }
        s = summary[b]
        s["identity_holds"] = s["legible_after_vae"] == s["legible_after_resize_K"] - s["lost_by_vae_L"] + s["reversals_illegible_to_legible"]
    rec = {"tool": "research/qwen/qv-reference/phase7_transitions.py",
           "inputs": {str(p.relative_to(ROOT)): hashlib.sha256(p.read_bytes()).hexdigest()
                      for p in (frozen, QV / "key-unblinded.json")},
           "identity": "legible_after_vae = K - L + reversals", "summary": summary, "table": table}
    (OUT / "phase7-transitions.json").write_text(json.dumps(rec, indent=1) + "\n")
    lines = ["# Phase 7 Q-V: per-element transitions (scaled input -> VAE round trip)", "",
             "Generated by `phase7_transitions.py` from the frozen `research/qwen/qv/review/SCORES-FROZEN.csv` "
             f"(sha256 `{rec['inputs']['research/qwen/qv/review/SCORES-FROZEN.csv'][:16]}…`) and `key-unblinded.json`. "
             "One rater (Phase 7). Nothing is re-scored. P/D/G = PRESERVED/DEGRADED/GARBLED; legible = P or D.", ""]
    for b in (512, 1024):
        s = summary[b]
        lines += [f"## {b}", "", "| element | after resize | after VAE | transition |", "|---|---|---|---|"]
        for x in (x for x in table if x["budget"] == b):
            lines.append(f"| {x['task']} {x['element']} ({x['sheet']}) | {x['after_resize']} | {x['after_vae']} | {x['transition']} |")
        lines += ["", f"K (legible after resize) = {s['legible_after_resize_K']}; L (of K, lost by the VAE) = "
                      f"{s['lost_by_vae_L']}; kept from K = {s['kept_from_K']}; reversals (illegible -> legible) = "
                      f"{s['reversals_illegible_to_legible']}; legible after VAE = {s['legible_after_vae']} "
                      f"(= K − L + reversals: {s['identity_holds']}).", ""]
    (OUT / "phase7-transitions.md").write_text("\n".join(lines))
    print(json.dumps(summary, indent=1))


if __name__ == "__main__":
    main()
