"""Generate the frozen G2 run chain (protocol.md §4) from task-manifest.json + source-manifest.json.

Each run goes through the production path (research/qwen/run_edit.sh mode `app` = `bin/photo-gen edit`, with the
1 Hz monitor and the watchdog), on the ORIGINAL downloaded camera file (so EXIF orientation, JPEG decoding and
staging are exercised exactly as for a user). Order: 512 primary R01..R16, 512 second seeds, 512 repeats, cooldown,
then the same at 1024. Run ids: G2-<budget>-<task>[-s2|-rep].

Usage: python3 research/editing/real-world/make_g2_chain.py > research/editing/real-world/g2-chain.sh"""
import json
import shlex
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
tasks = json.loads((HERE / "task-manifest.json").read_text())["tasks"]
sources = json.loads((HERE / "source-manifest.json").read_text())["sources"]

lines = ["#!/bin/zsh",
         "# G2 chain (generated by make_g2_chain.py; frozen in a commit before launch; protocol.md §4).",
         "# Launch: nohup zsh research/editing/real-world/g2-chain.sh > research/editing/real-world/g2-chain.log 2>&1 < /dev/null & disown",
         "# Marker: G2_CHAIN_DONE. run_edit.sh bypasses data/gpu.lock: run no photo-gen jobs while this chain runs.",
         "main() {", "set -u", "cd ~/Dev/photo-gen", 'echo "G2_CHAIN_START $(date) git=$(git rev-parse HEAD)"']


def run(rid, task, budget, seed):
    src = ROOT / sources[task["source"]]["local_path"]
    return (f"zsh research/qwen/run_edit.sh {rid} app {shlex.quote(str(src))} {budget} {seed} "
            f"{shlex.quote(task['instruction'])}; sleep 20")


for i, budget in enumerate((512, 1024)):
    if i:
        lines += ['echo "COOLDOWN $(date +%T)"; sleep 120']
    lines += [f"# ---- {budget}: primary ----"] + [run(f"G2-{budget}-{t['id']}", t, budget, t["seed"]) for t in tasks]
    lines += [f"# ---- {budget}: second seed (hard cases) ----"] + \
        [run(f"G2-{budget}-{t['id']}-s2", t, budget, t["second_seed"]) for t in tasks if t.get("second_seed")]
    lines += [f"# ---- {budget}: repeats (determinism) ----"] + \
        [run(f"G2-{budget}-{t['id']}-rep", t, budget, t["seed"]) for t in tasks if budget in t.get("repeat_at", [])]
lines += ['echo "G2_CHAIN_DONE $(date)"', "}",
          'main "$@"; exit $?   # exit here: never read past this line, even if the file grows mid-run']
print("\n".join(lines))
