"""Generate the frozen Q-V chain (research/qwen/qv/PROTOCOL.md section 5) from the G2 run records: the pipeline-
equivalence gate first (the chain stops unless it passes), then one fresh-process VAE round trip per (budget, task)
and a second, repeat process for each (determinism). Staged inputs come from the G2 sidecars.

Usage: mflux/.venv/bin/python3.12 research/qwen/qv/make_qv_chain.py > research/qwen/qv/qv-chain.sh
Run as: nohup zsh research/qwen/qv/qv-chain.sh > research/qwen/qv/qv-chain.log 2>&1 < /dev/null & disown
Marker: QV_CHAIN_DONE (or QV_CHAIN_STOPPED_GATE_FAILED)."""
import json
import shlex
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]


def main() -> None:
    lines = ["#!/bin/zsh", "# GENERATED by research/qwen/qv/make_qv_chain.py; frozen before any Q-V run (PROTOCOL.md section 5).",
             "main() {", "cd ~/Dev/photo-gen", 'echo "QV_CHAIN_START $(date) git=$(git rev-parse HEAD)"',
             "zsh research/qwen/run_edit.sh QVGATE-512-E05 qv:gate - 512 0 - 3",
             "if ! mflux/.venv/bin/python3.12 -c \"import json,sys; d=json.load(open('research/qwen/runs/QVGATE-512-E05/result.json')); "
             "sys.exit(0 if d.get('pass') else 1)\"; then echo QV_CHAIN_STOPPED_GATE_FAILED; return 1; fi",
             "sleep 10"]
    for budget in (512, 1024):
        for task in ("R02", "R12", "R15"):
            sc = json.loads((ROOT / f"research/qwen/runs/G2-{budget}-{task}/sidecar.json").read_text())
            for rep in ("a", "b"):
                args = ["zsh", "research/qwen/run_edit.sh", f"QV-{budget}-{task}-{rep}", "qv:roundtrip",
                        sc["input_image"]["staged_path"], str(budget), "0", "-", "0"]
                lines += [" ".join(shlex.quote(a) for a in args), "sleep 5"]
    lines += ['echo "QV_CHAIN_DONE $(date)"', "}", 'main "$@"; exit $?']
    print("\n".join(lines))


if __name__ == "__main__":
    main()
