#!/bin/zsh
# GENERATED by research/qwen/qv/make_qv_chain.py; frozen before any Q-V run (PROTOCOL.md section 5).
main() {
cd ~/Dev/photo-gen
echo "QV_CHAIN_START $(date) git=$(git rev-parse HEAD)"
zsh research/qwen/run_edit.sh QVGATE-512-E05 qv:gate - 512 0 - 3
if ! mflux/.venv/bin/python3.12 -c "import json,sys; d=json.load(open('research/qwen/runs/QVGATE-512-E05/result.json')); sys.exit(0 if d.get('pass') else 1)"; then echo QV_CHAIN_STOPPED_GATE_FAILED; return 1; fi
sleep 10
zsh research/qwen/run_edit.sh QV-512-R02-a qv:roundtrip /Users/nckandrw/Dev/photo-gen/data/inputs/73670d26a44b0281bab6f60d37d4adb69f77a1a836ea9dea0cb306a7a21239e9.png 512 0 - 0
sleep 5
zsh research/qwen/run_edit.sh QV-512-R02-b qv:roundtrip /Users/nckandrw/Dev/photo-gen/data/inputs/73670d26a44b0281bab6f60d37d4adb69f77a1a836ea9dea0cb306a7a21239e9.png 512 0 - 0
sleep 5
zsh research/qwen/run_edit.sh QV-512-R12-a qv:roundtrip /Users/nckandrw/Dev/photo-gen/data/inputs/6766f9603ea0a60bf338e6bd40308d3bdce19b0566379b2f0fab8b94e228e301.png 512 0 - 0
sleep 5
zsh research/qwen/run_edit.sh QV-512-R12-b qv:roundtrip /Users/nckandrw/Dev/photo-gen/data/inputs/6766f9603ea0a60bf338e6bd40308d3bdce19b0566379b2f0fab8b94e228e301.png 512 0 - 0
sleep 5
zsh research/qwen/run_edit.sh QV-512-R15-a qv:roundtrip /Users/nckandrw/Dev/photo-gen/data/inputs/d3c22ffaae47572c1515a0d7f58231cc1ce88055b344c11e7d58c5561442335e.png 512 0 - 0
sleep 5
zsh research/qwen/run_edit.sh QV-512-R15-b qv:roundtrip /Users/nckandrw/Dev/photo-gen/data/inputs/d3c22ffaae47572c1515a0d7f58231cc1ce88055b344c11e7d58c5561442335e.png 512 0 - 0
sleep 5
zsh research/qwen/run_edit.sh QV-1024-R02-a qv:roundtrip /Users/nckandrw/Dev/photo-gen/data/inputs/73670d26a44b0281bab6f60d37d4adb69f77a1a836ea9dea0cb306a7a21239e9.png 1024 0 - 0
sleep 5
zsh research/qwen/run_edit.sh QV-1024-R02-b qv:roundtrip /Users/nckandrw/Dev/photo-gen/data/inputs/73670d26a44b0281bab6f60d37d4adb69f77a1a836ea9dea0cb306a7a21239e9.png 1024 0 - 0
sleep 5
zsh research/qwen/run_edit.sh QV-1024-R12-a qv:roundtrip /Users/nckandrw/Dev/photo-gen/data/inputs/6766f9603ea0a60bf338e6bd40308d3bdce19b0566379b2f0fab8b94e228e301.png 1024 0 - 0
sleep 5
zsh research/qwen/run_edit.sh QV-1024-R12-b qv:roundtrip /Users/nckandrw/Dev/photo-gen/data/inputs/6766f9603ea0a60bf338e6bd40308d3bdce19b0566379b2f0fab8b94e228e301.png 1024 0 - 0
sleep 5
zsh research/qwen/run_edit.sh QV-1024-R15-a qv:roundtrip /Users/nckandrw/Dev/photo-gen/data/inputs/d3c22ffaae47572c1515a0d7f58231cc1ce88055b344c11e7d58c5561442335e.png 1024 0 - 0
sleep 5
zsh research/qwen/run_edit.sh QV-1024-R15-b qv:roundtrip /Users/nckandrw/Dev/photo-gen/data/inputs/d3c22ffaae47572c1515a0d7f58231cc1ce88055b344c11e7d58c5561442335e.png 1024 0 - 0
sleep 5
echo "QV_CHAIN_DONE $(date)"
}
main "$@"; exit $?
