"""Generate the frozen Q-Q chain (research/qwen/qq/PROTOCOL.md §4) from the G2 run records, so every q4/q8 run gets
exactly the staged input, instruction and seed of its G2 counterpart.

Usage: mflux/.venv/bin/python3.12 research/qwen/qq/make_qq_chain.py <budgets, e.g. 512,1024> > research/qwen/qq/qq-chain.sh
Order per budget block (arms balanced over positions; q8 repeat last): R02 q4, R02 q8, R12 q8, R12 q4, R15 q4, R15 q8,
R12-s2 q8, R12-s2 q4, R12 q8 repeat. 20 s between runs; 120 s cooldown between blocks. Marker: QQ_CHAIN_DONE."""
import json
import shlex
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
ORDER = [("R02", "", "q4", ""), ("R02", "", "q8", ""), ("R12", "", "q8", ""), ("R12", "", "q4", ""),
         ("R15", "", "q4", ""), ("R15", "", "q8", ""), ("R12", "-s2", "q8", ""), ("R12", "-s2", "q4", ""),
         ("R12", "", "q8", "-rep")]


def runs(budget: int) -> list[str]:
    lines = []
    for task, kind, arm, rep in ORDER:
        g2 = ROOT / f"research/qwen/runs/G2-{budget}-{task}{kind}"
        sc = json.loads((g2 / "sidecar.json").read_text())
        rid = f"QQ-{budget}-{task}{kind}-{arm}{rep}"
        args = ["zsh", "research/qwen/run_edit.sh", rid, f"qq:{arm}", sc["input_image"]["staged_path"], str(budget),
                str(sc["seed"]), sc["prompt"], "40"]
        lines += [" ".join(shlex.quote(a) for a in args), "sleep 20"]
    return lines


def main(budgets: str) -> None:
    out = ["#!/bin/zsh", "# GENERATED by research/qwen/qq/make_qq_chain.py; frozen before any Q-Q chain run (PROTOCOL.md §4).",
           "# Run as: nohup zsh research/qwen/qq/qq-chain.sh > research/qwen/qq/qq-chain.log 2>&1 < /dev/null & disown",
           "main() {", "cd ~/Dev/photo-gen", 'echo "QQ_CHAIN_START $(date) git=$(git rev-parse HEAD)"']
    for i, b in enumerate(int(x) for x in budgets.split(",")):
        if i:
            out += ['echo "COOLDOWN $(date +%T)"', "sleep 120"]
        out += runs(b)
    out += ['echo "QQ_CHAIN_DONE $(date)"', "}", 'main "$@"; exit $?']
    print("\n".join(out))


if __name__ == "__main__":
    main(sys.argv[1])
