#!/bin/zsh
# GENERATED by research/qwen/qq/make_qq_chain.py; frozen before any Q-Q chain run (PROTOCOL.md §4).
# Run as: nohup zsh research/qwen/qq/qq-chain.sh > research/qwen/qq/qq-chain.log 2>&1 < /dev/null & disown
main() {
cd ~/Dev/photo-gen
echo "QQ_CHAIN_START $(date) git=$(git rev-parse HEAD)"
zsh research/qwen/run_edit.sh QQ-512-R02-q4 qq:q4 /Users/nckandrw/Dev/photo-gen/data/inputs/73670d26a44b0281bab6f60d37d4adb69f77a1a836ea9dea0cb306a7a21239e9.png 512 2510702 'Remove the dark grey van parked in front of the building.' 40
sleep 20
zsh research/qwen/run_edit.sh QQ-512-R02-q8 qq:q8 /Users/nckandrw/Dev/photo-gen/data/inputs/73670d26a44b0281bab6f60d37d4adb69f77a1a836ea9dea0cb306a7a21239e9.png 512 2510702 'Remove the dark grey van parked in front of the building.' 40
sleep 20
zsh research/qwen/run_edit.sh QQ-512-R12-q8 qq:q8 /Users/nckandrw/Dev/photo-gen/data/inputs/6766f9603ea0a60bf338e6bd40308d3bdce19b0566379b2f0fab8b94e228e301.png 512 2510712 'Remove the man in dark clothes walking towards the camera in the middle of the street.' 40
sleep 20
zsh research/qwen/run_edit.sh QQ-512-R12-q4 qq:q4 /Users/nckandrw/Dev/photo-gen/data/inputs/6766f9603ea0a60bf338e6bd40308d3bdce19b0566379b2f0fab8b94e228e301.png 512 2510712 'Remove the man in dark clothes walking towards the camera in the middle of the street.' 40
sleep 20
zsh research/qwen/run_edit.sh QQ-512-R15-q4 qq:q4 /Users/nckandrw/Dev/photo-gen/data/inputs/d3c22ffaae47572c1515a0d7f58231cc1ce88055b344c11e7d58c5561442335e.png 512 2510715 'Paint the brick wall around the shop white. Keep the shop sign and all lettering exactly as they are.' 40
sleep 20
zsh research/qwen/run_edit.sh QQ-512-R15-q8 qq:q8 /Users/nckandrw/Dev/photo-gen/data/inputs/d3c22ffaae47572c1515a0d7f58231cc1ce88055b344c11e7d58c5561442335e.png 512 2510715 'Paint the brick wall around the shop white. Keep the shop sign and all lettering exactly as they are.' 40
sleep 20
zsh research/qwen/run_edit.sh QQ-512-R12-s2-q8 qq:q8 /Users/nckandrw/Dev/photo-gen/data/inputs/6766f9603ea0a60bf338e6bd40308d3bdce19b0566379b2f0fab8b94e228e301.png 512 2520712 'Remove the man in dark clothes walking towards the camera in the middle of the street.' 40
sleep 20
zsh research/qwen/run_edit.sh QQ-512-R12-s2-q4 qq:q4 /Users/nckandrw/Dev/photo-gen/data/inputs/6766f9603ea0a60bf338e6bd40308d3bdce19b0566379b2f0fab8b94e228e301.png 512 2520712 'Remove the man in dark clothes walking towards the camera in the middle of the street.' 40
sleep 20
zsh research/qwen/run_edit.sh QQ-512-R12-q8-rep qq:q8 /Users/nckandrw/Dev/photo-gen/data/inputs/6766f9603ea0a60bf338e6bd40308d3bdce19b0566379b2f0fab8b94e228e301.png 512 2510712 'Remove the man in dark clothes walking towards the camera in the middle of the street.' 40
sleep 20
echo "COOLDOWN $(date +%T)"
sleep 120
zsh research/qwen/run_edit.sh QQ-1024-R02-q4 qq:q4 /Users/nckandrw/Dev/photo-gen/data/inputs/73670d26a44b0281bab6f60d37d4adb69f77a1a836ea9dea0cb306a7a21239e9.png 1024 2510702 'Remove the dark grey van parked in front of the building.' 40
sleep 20
zsh research/qwen/run_edit.sh QQ-1024-R02-q8 qq:q8 /Users/nckandrw/Dev/photo-gen/data/inputs/73670d26a44b0281bab6f60d37d4adb69f77a1a836ea9dea0cb306a7a21239e9.png 1024 2510702 'Remove the dark grey van parked in front of the building.' 40
sleep 20
zsh research/qwen/run_edit.sh QQ-1024-R12-q8 qq:q8 /Users/nckandrw/Dev/photo-gen/data/inputs/6766f9603ea0a60bf338e6bd40308d3bdce19b0566379b2f0fab8b94e228e301.png 1024 2510712 'Remove the man in dark clothes walking towards the camera in the middle of the street.' 40
sleep 20
zsh research/qwen/run_edit.sh QQ-1024-R12-q4 qq:q4 /Users/nckandrw/Dev/photo-gen/data/inputs/6766f9603ea0a60bf338e6bd40308d3bdce19b0566379b2f0fab8b94e228e301.png 1024 2510712 'Remove the man in dark clothes walking towards the camera in the middle of the street.' 40
sleep 20
zsh research/qwen/run_edit.sh QQ-1024-R15-q4 qq:q4 /Users/nckandrw/Dev/photo-gen/data/inputs/d3c22ffaae47572c1515a0d7f58231cc1ce88055b344c11e7d58c5561442335e.png 1024 2510715 'Paint the brick wall around the shop white. Keep the shop sign and all lettering exactly as they are.' 40
sleep 20
zsh research/qwen/run_edit.sh QQ-1024-R15-q8 qq:q8 /Users/nckandrw/Dev/photo-gen/data/inputs/d3c22ffaae47572c1515a0d7f58231cc1ce88055b344c11e7d58c5561442335e.png 1024 2510715 'Paint the brick wall around the shop white. Keep the shop sign and all lettering exactly as they are.' 40
sleep 20
zsh research/qwen/run_edit.sh QQ-1024-R12-s2-q8 qq:q8 /Users/nckandrw/Dev/photo-gen/data/inputs/6766f9603ea0a60bf338e6bd40308d3bdce19b0566379b2f0fab8b94e228e301.png 1024 2520712 'Remove the man in dark clothes walking towards the camera in the middle of the street.' 40
sleep 20
zsh research/qwen/run_edit.sh QQ-1024-R12-s2-q4 qq:q4 /Users/nckandrw/Dev/photo-gen/data/inputs/6766f9603ea0a60bf338e6bd40308d3bdce19b0566379b2f0fab8b94e228e301.png 1024 2520712 'Remove the man in dark clothes walking towards the camera in the middle of the street.' 40
sleep 20
zsh research/qwen/run_edit.sh QQ-1024-R12-q8-rep qq:q8 /Users/nckandrw/Dev/photo-gen/data/inputs/6766f9603ea0a60bf338e6bd40308d3bdce19b0566379b2f0fab8b94e228e301.png 1024 2510712 'Remove the man in dark clothes walking towards the camera in the middle of the street.' 40
sleep 20
echo "QQ_CHAIN_DONE $(date)"
}
main "$@"; exit $?
