#!/bin/zsh
# GENERATED by research/qwen/make_g0_chain.py: do not edit (regenerate instead).
# G0 capability/reliability suites. Marker: G0_CHAIN_DONE
main() {
cd ~/Dev/photo-gen
echo "G0 start $(date +%T) head=$(git rev-parse --short HEAD)"
zsh research/qwen/run_edit.sh G0-512-E01 app /Users/nckandrw/Dev/photo-gen/data/outputs/2026/10/06/20261006T165054Z-9afd59-editsrc-E01-s1101.png 512 42 'Change the red car to a blue motorcycle while preserving the street, lighting, perspective, and all other objects.' 40; sleep 20
zsh research/qwen/run_edit.sh G0-512-E02 app /Users/nckandrw/Dev/photo-gen/data/outputs/2026/10/06/20261006T165314Z-37f899-editsrc-E02-s1202.png 512 42 'Give the panda a blue scarf.' 40; sleep 20
zsh research/qwen/run_edit.sh G0-512-E03 app /Users/nckandrw/Dev/photo-gen/data/outputs/2026/10/06/20261006T165539Z-627114-editsrc-E03-s1303.png 512 42 'Remove the coffee mug. Keep everything else unchanged.' 40; sleep 20
zsh research/qwen/run_edit.sh G0-512-E04 app /Users/nckandrw/Dev/photo-gen/data/outputs/2026/10/06/20261006T165809Z-334d7a-editsrc-E04-s1404.png 512 42 'Change the jacket to dark green. Preserve the person'"'"'s face and pose.' 40; sleep 20
zsh research/qwen/run_edit.sh G0-512-E05 app /Users/nckandrw/Dev/photo-gen/data/outputs/2026/10/06/20261006T170025Z-9f37b9-editsrc-E05-s1505.png 512 42 'Change the background to a sunset beach' 40; sleep 20
zsh research/qwen/run_edit.sh G0-512-E06 app /Users/nckandrw/Dev/photo-gen/data/outputs/2026/10/06/20261006T170239Z-cc260a-editsrc-E06-s1606.png 512 42 'Turn this photo into a watercolor painting while keeping the composition unchanged.' 40; sleep 20
zsh research/qwen/run_edit.sh G0-512-E07 app /Users/nckandrw/Dev/photo-gen/data/outputs/2026/10/06/20261006T170453Z-1fd2ad-editsrc-E07-s1707.png 512 42 'Change the hair color to blond.' 40; sleep 20
zsh research/qwen/run_edit.sh G0-512-E08 app /Users/nckandrw/Dev/photo-gen/data/outputs/2026/10/06/20261006T170707Z-aec4f6-editsrc-E08-s1808.png 512 42 'Replace the bananas with pineapples. Do not change anything else.' 40; sleep 20
zsh research/qwen/run_edit.sh G0-512-E09 app /Users/nckandrw/Dev/photo-gen/data/outputs/2026/10/06/20261006T170919Z-b85860-editsrc-E09-s1909.png 512 42 'Turn the scene into nighttime with the floor lamp switched on, keeping the furniture and layout unchanged.' 40; sleep 20
zsh research/qwen/run_edit.sh G0-512-E10 app /Users/nckandrw/Dev/photo-gen/data/outputs/2026/10/06/20261006T171126Z-76fd40-editsrc-E10-s2010.png 512 42 'Change the flower to a red tulip. Keep the text exactly as it is.' 40; sleep 20
zsh research/qwen/run_edit.sh G0-512-E11 app /Users/nckandrw/Dev/photo-gen/data/outputs/2026/10/06/20261006T171338Z-f0f509-editsrc-E11-s2111.png 512 42 'Replace the text "BAKERY" with "COFFEE", keeping the same font of the original text.' 40; sleep 20
zsh research/qwen/run_edit.sh G0-512-E05-repeat app /Users/nckandrw/Dev/photo-gen/data/outputs/2026/10/06/20261006T170025Z-9f37b9-editsrc-E05-s1505.png 512 42 'Change the background to a sunset beach' 40; sleep 20
echo "cooldown start $(date +%T)"
sleep 600
zsh research/qwen/run_edit.sh G0-1024-E05-cold app /Users/nckandrw/Dev/photo-gen/data/outputs/2026/10/06/20261006T170025Z-9f37b9-editsrc-E05-s1505.png 1024 42 'Change the background to a sunset beach' 40; sleep 20
zsh research/qwen/run_edit.sh G0-1024-E01 app /Users/nckandrw/Dev/photo-gen/data/outputs/2026/10/06/20261006T165054Z-9afd59-editsrc-E01-s1101.png 1024 42 'Change the red car to a blue motorcycle while preserving the street, lighting, perspective, and all other objects.' 40; sleep 20
zsh research/qwen/run_edit.sh G0-1024-E02 app /Users/nckandrw/Dev/photo-gen/data/outputs/2026/10/06/20261006T165314Z-37f899-editsrc-E02-s1202.png 1024 42 'Give the panda a blue scarf.' 40; sleep 20
zsh research/qwen/run_edit.sh G0-1024-E03 app /Users/nckandrw/Dev/photo-gen/data/outputs/2026/10/06/20261006T165539Z-627114-editsrc-E03-s1303.png 1024 42 'Remove the coffee mug. Keep everything else unchanged.' 40; sleep 20
zsh research/qwen/run_edit.sh G0-1024-E04 app /Users/nckandrw/Dev/photo-gen/data/outputs/2026/10/06/20261006T165809Z-334d7a-editsrc-E04-s1404.png 1024 42 'Change the jacket to dark green. Preserve the person'"'"'s face and pose.' 40; sleep 20
zsh research/qwen/run_edit.sh G0-1024-E06 app /Users/nckandrw/Dev/photo-gen/data/outputs/2026/10/06/20261006T170239Z-cc260a-editsrc-E06-s1606.png 1024 42 'Turn this photo into a watercolor painting while keeping the composition unchanged.' 40; sleep 20
zsh research/qwen/run_edit.sh G0-1024-E07 app /Users/nckandrw/Dev/photo-gen/data/outputs/2026/10/06/20261006T170453Z-1fd2ad-editsrc-E07-s1707.png 1024 42 'Change the hair color to blond.' 40; sleep 20
zsh research/qwen/run_edit.sh G0-1024-E08 app /Users/nckandrw/Dev/photo-gen/data/outputs/2026/10/06/20261006T170707Z-aec4f6-editsrc-E08-s1808.png 1024 42 'Replace the bananas with pineapples. Do not change anything else.' 40; sleep 20
zsh research/qwen/run_edit.sh G0-1024-E09 app /Users/nckandrw/Dev/photo-gen/data/outputs/2026/10/06/20261006T170919Z-b85860-editsrc-E09-s1909.png 1024 42 'Turn the scene into nighttime with the floor lamp switched on, keeping the furniture and layout unchanged.' 40; sleep 20
zsh research/qwen/run_edit.sh G0-1024-E10 app /Users/nckandrw/Dev/photo-gen/data/outputs/2026/10/06/20261006T171126Z-76fd40-editsrc-E10-s2010.png 1024 42 'Change the flower to a red tulip. Keep the text exactly as it is.' 40; sleep 20
zsh research/qwen/run_edit.sh G0-1024-E11 app /Users/nckandrw/Dev/photo-gen/data/outputs/2026/10/06/20261006T171338Z-f0f509-editsrc-E11-s2111.png 1024 42 'Replace the text "BAKERY" with "COFFEE", keeping the same font of the original text.' 40; sleep 20
zsh research/qwen/run_edit.sh G0-1024-E05-repeat app /Users/nckandrw/Dev/photo-gen/data/outputs/2026/10/06/20261006T170025Z-9f37b9-editsrc-E05-s1505.png 1024 42 'Change the background to a sunset beach' 40; sleep 20
echo "G0_CHAIN_DONE $(date +%T)"
}
main "$@"; exit $?
