#!/bin/zsh
# GENERATED by research/qwen/g1_prepare.py. G1 bounded runtime A/B. Marker: G1_CHAIN_DONE
# Stop rule: an sd.cpp edit longer than 20 min or a watchdog abort ends the chain (recorded result).
main() {
cd ~/Dev/photo-gen
zsh research/qwen/run_edit.sh G1-sdcpp-SMOKE sdcpp /Users/nckandrw/Dev/photo-gen/research/qwen/g1/refs/SMOKE-512.png 512 42 'Change the background to a sunset beach' 40
if grep -q ABORT research/qwen/runs/G1-sdcpp-SMOKE/conditions.txt || (( $(grep -o 'wall_s=[0-9]*' research/qwen/runs/G1-sdcpp-SMOKE/conditions.txt | cut -d= -f2) > 1200 )); then echo "G1 STOP after G1-sdcpp-SMOKE"; echo G1_CHAIN_DONE; return 0; fi; sleep 30
zsh research/qwen/run_edit.sh G1-mflux-E01-parity app /Users/nckandrw/Dev/photo-gen/research/qwen/g1/refs/E01-512.png 512 42 'Change the red car to a blue motorcycle while preserving the street, lighting, perspective, and all other objects.' 40; sleep 20
zsh research/qwen/run_edit.sh G1-sdcpp-E01 sdcpp /Users/nckandrw/Dev/photo-gen/research/qwen/g1/refs/E01-512.png 512 42 'Change the red car to a blue motorcycle while preserving the street, lighting, perspective, and all other objects.' 40
if grep -q ABORT research/qwen/runs/G1-sdcpp-E01/conditions.txt || (( $(grep -o 'wall_s=[0-9]*' research/qwen/runs/G1-sdcpp-E01/conditions.txt | cut -d= -f2) > 1200 )); then echo "G1 STOP after G1-sdcpp-E01"; echo G1_CHAIN_DONE; return 0; fi; sleep 30
zsh research/qwen/run_edit.sh G1-sdcpp-E05 sdcpp /Users/nckandrw/Dev/photo-gen/research/qwen/g1/refs/E05-512.png 512 42 'Change the background to a sunset beach' 40
if grep -q ABORT research/qwen/runs/G1-sdcpp-E05/conditions.txt || (( $(grep -o 'wall_s=[0-9]*' research/qwen/runs/G1-sdcpp-E05/conditions.txt | cut -d= -f2) > 1200 )); then echo "G1 STOP after G1-sdcpp-E05"; echo G1_CHAIN_DONE; return 0; fi; sleep 30
zsh research/qwen/run_edit.sh G1-sdcpp-E07 sdcpp /Users/nckandrw/Dev/photo-gen/research/qwen/g1/refs/E07-512.png 512 42 'Change the hair color to blond.' 40
if grep -q ABORT research/qwen/runs/G1-sdcpp-E07/conditions.txt || (( $(grep -o 'wall_s=[0-9]*' research/qwen/runs/G1-sdcpp-E07/conditions.txt | cut -d= -f2) > 1200 )); then echo "G1 STOP after G1-sdcpp-E07"; echo G1_CHAIN_DONE; return 0; fi; sleep 30
zsh research/qwen/run_edit.sh G1-sdcpp-E11 sdcpp /Users/nckandrw/Dev/photo-gen/research/qwen/g1/refs/E11-512.png 512 42 'Replace the text "BAKERY" with "COFFEE", keeping the same font of the original text.' 40
if grep -q ABORT research/qwen/runs/G1-sdcpp-E11/conditions.txt || (( $(grep -o 'wall_s=[0-9]*' research/qwen/runs/G1-sdcpp-E11/conditions.txt | cut -d= -f2) > 1200 )); then echo "G1 STOP after G1-sdcpp-E11"; echo G1_CHAIN_DONE; return 0; fi; sleep 30
echo G1_CHAIN_DONE
}
main "$@"; exit $?
