"""G1 (bounded runtime A/B, research/editing/README.md §5): build like-for-like 512 references and the chain.

Both runtimes get the SAME pre-resized reference: the accepted 1024² source resized exactly as mflux 0.21.0 does
internally (open -> RGBA -> resize to QwenImage21LatentCreator.dimensions(512, ratio) with LANCZOS), saved as an
opaque RGB PNG. mflux then sees a no-op resize (same size), so its G1 arm must reproduce the G0-512 pixels exactly
(checked by one run); sd.cpp gets a 512² reference instead of a 1024² one (no hidden 4096-token reference).
Subset (bounded): E01 replacement, E05 background, E07 localized, E11 text. Calibration first: the smoke apple.
Writes research/qwen/g1/refs/*.png (gitignored), research/qwen/g1/refs.json, research/qwen/g1-chain.sh."""
import hashlib
import json
import shlex
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "app"))
from photogen.runtimes.mflux_qwen_edit import output_dimensions  # noqa: E402  (== mflux 0.21.0, tested)

SUBSET = ["E01", "E05", "E07", "E11"]
suite = {t["id"]: t for t in json.loads((ROOT / "research/editing/suite-v1.json").read_text())["tests"]}
sources = json.loads((ROOT / "research/editing/sources.json").read_text())["accepted"]
out = ROOT / "research/qwen/g1/refs"
out.mkdir(parents=True, exist_ok=True)
smoke_src = ROOT / "data/inputs/befe1b3c8af5424cc5f65868fec96938bfac782238f46c18652244fada3bdd42.png"
items = {"SMOKE": (smoke_src, "Change the background to a sunset beach")}
items.update({tid: (Path(sources[tid]["output_path"]), suite[tid]["instruction"]) for tid in SUBSET})
refs = {}
for tid, (src, instr) in items.items():
    im = Image.open(src).convert("RGBA")
    size = output_dimensions(512, im.width / im.height)
    r = im.resize(size, Image.Resampling.LANCZOS)
    assert r.getchannel("A").getextrema() == (255, 255)
    rgb = r.convert("RGB")
    p = out / f"{tid}-512.png"
    rgb.save(p)
    refs[tid] = {"source": str(src), "ref": str(p), "size": list(size), "instruction": instr,
                 "ref_pixel_sha256": hashlib.sha256(rgb.tobytes()).hexdigest()}
(ROOT / "research/qwen/g1/refs.json").write_text(json.dumps(refs, indent=1))
lines = ["#!/bin/zsh", "# GENERATED by research/qwen/g1_prepare.py. G1 bounded runtime A/B. Marker: G1_CHAIN_DONE",
         "# Stop rule: an sd.cpp edit longer than 20 min or a watchdog abort ends the chain (recorded result).", "main() {",
         "cd ~/Dev/photo-gen"]


def edit(rid, mode, tid):
    r = refs[tid]
    return (f"zsh research/qwen/run_edit.sh {rid} {mode} {shlex.quote(r['ref'])} 512 42 "
            f"{shlex.quote(r['instruction'])} 40")


def guard(rid):
    return (f"if grep -q ABORT research/qwen/runs/{rid}/conditions.txt || "
            f"(( $(grep -o 'wall_s=[0-9]*' research/qwen/runs/{rid}/conditions.txt | cut -d= -f2) > 1200 )); then "
            f"echo \"G1 STOP after {rid}\"; echo G1_CHAIN_DONE; return 0; fi; sleep 30")


lines += [edit("G1-sdcpp-SMOKE", "sdcpp", "SMOKE"), guard("G1-sdcpp-SMOKE"),
          edit("G1-mflux-E01-parity", "app", "E01") + "; sleep 20"]
for tid in SUBSET:
    lines += [edit(f"G1-sdcpp-{tid}", "sdcpp", tid), guard(f"G1-sdcpp-{tid}")]
lines += ["echo G1_CHAIN_DONE", "}", "main \"$@\"; exit $?"]
(ROOT / "research/qwen/g1-chain.sh").write_text("\n".join(lines) + "\n")
print(json.dumps({k: (v["size"], v["ref_pixel_sha256"][:12]) for k, v in refs.items()}))
