"""Write research/qwen/g0-chain.sh: the explicit, sequential G0 run list (research/editing/README.md §4).

Order (decided before the chain is generated):
  512 suite: E01..E11, then E05 repeat (determinism).
  10 min idle cooldown.
  1024 suite: E05 FIRST (= the cold 1024² baseline of QWEN-EDITING-BASELINE.md), then the other 10, then E05 repeat.
Every edit uses the production path (bin/photo-gen edit; job system, staging, edit worker with the production
lifecycle), seed 42, 40 steps (suite edit_parameters). Marker: G0_CHAIN_DONE.
Usage: python3 research/qwen/make_g0_chain.py   (reads research/editing/{suite-v1,sources}.json)"""
import json
import shlex
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
suite = json.loads((ROOT / "research/editing/suite-v1.json").read_text())
sources = json.loads((ROOT / "research/editing/sources.json").read_text())["accepted"]
ep = suite["edit_parameters"]
tests = {t["id"]: t for t in suite["tests"]}
ids = [t["id"] for t in suite["tests"]]


def run(rid, tid, res):
    src = sources[tid]["output_path"]
    return (f"zsh research/qwen/run_edit.sh {rid} app {shlex.quote(src)} {res} {ep['seed']} "
            f"{shlex.quote(tests[tid]['instruction'])} {ep['steps']}; sleep 20")


lines = ["#!/bin/zsh", "# GENERATED by research/qwen/make_g0_chain.py: do not edit (regenerate instead).",
         "# G0 capability/reliability suites. Marker: G0_CHAIN_DONE", "main() {", "cd ~/Dev/photo-gen",
         "echo \"G0 start $(date +%T) head=$(git rev-parse --short HEAD)\""]
for tid in ids:
    lines.append(run(f"G0-512-{tid}", tid, 512))
lines.append(run("G0-512-E05-repeat", "E05", 512))
lines += ["echo \"cooldown start $(date +%T)\"", "sleep 600"]
lines.append(run("G0-1024-E05-cold", "E05", 1024))
for tid in ids:
    if tid != "E05":
        lines.append(run(f"G0-1024-{tid}", tid, 1024))
lines.append(run("G0-1024-E05-repeat", "E05", 1024))
lines += ["echo \"G0_CHAIN_DONE $(date +%T)\"", "}", "main \"$@\"; exit $?"]
(ROOT / "research/qwen/g0-chain.sh").write_text("\n".join(lines) + "\n")
print(f"wrote research/qwen/g0-chain.sh ({len(ids) * 2 + 2} edits)")
